version: '3'

services:
  php:
    container_name: php
    build: ./docker/php
    volumes:
      - ./webapp:/var/www/webapp
      - ./docker/php/bash_history:/root/.bash_history
      - ./docker/php/vimrc:/root/.vimrc
      - ./docker/php/gitconfig:/root/.gitconfig
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - webapp-net

  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./webapp:/var/www/webapp
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/bash_history:/root/.bash_history
    depends_on:
      - php
    networks:
      - webapp-net

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webapp
      MYSQL_USER: webapp
      MYSQL_PASSWORD: webapp
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
      - ./docker/mysql/log:/var/log/mysql
      - ./docker/mysql/bash_history:/root/.bash_history
    ports:
      - 3306:3306
    user: "1000:1000"
    depends_on:
      - php
    networks:
      - webapp-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql:db
    ports:
      - 8080:80
    volumes:
      - ./docker/phpmyadmin:/sessions
    networks:
      - webapp-net

networks:
  webapp-net:
    driver: bridge
